language: php

php:
  - 5.4
  - 5.5

env:
  - NETCOMMONS_VERSION=master DB=mysql
  - NETCOMMONS_VERSION=master DB=pgsql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp_test;'; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'CREATE DATABASE cakephp_test;' -U postgres; fi"
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - export PLUGIN_NAME=`basename $TRAVIS_BUILD_DIR`
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
  - cp -r ../$PLUGIN_NAME plugins
  - cp -r ../$PLUGIN_NAME app/Plugin/
  - chmod -R 777 app/tmp
  - mkdir -p build/logs
  - pear channel-discover pear.cakephp.org
  - pear install --alldeps cakephp/CakePHP_CodeSniffer
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install phpmd/PHP_PMD
  - pear config-set auto_discover 1
  - pear install pear.phpunit.de/phpcpd
  - phpenv rehash
  - set +H
  - cp app/Config/database.php.test app/Config/database.php

script:
  - ./lib/Cake/Console/cake test $PLUGIN_NAME All$PLUGIN_NAME --stderr
  - phpcs -p --extensions=php --standard=CakePHP --ignore=app/Config/Migration/,app/Config/database.php,app/Plugin/DebugKit,app/Plugin/Migrations,app/Plugin/MobileDetect app
  - phpmd app text ruleset/phpmd.xml --exclude $NETCOMMONS_BUILD_DIR/app/Config/Migration,$NETCOMMONS_BUILD_DIR/app/Plugin/DebugKit,$NETCOMMONS_BUILD_DIR/app/Plugin/Migrations,$NETCOMMONS_BUILD_DIR/app/Plugin/MobileDetect
  - phpcpd --exclude Test --exclude Config --exclude app/Config/database.php --exclude app/Plugin/DebugKit --exclude app/Plugin/Migrations --exclude app/Plugin/MobileDetect app

after_script:
  - php vendors/bin/coveralls -vvv

notifications:
  email:
    recipients:
      - netcommons3@googlegroups.com
    on_success: never  # default: change
    on_failure: always # default: always
